language: php
dist: trusty
sudo: false

php:
  - 7.3
  - 7.4
  - 8.0
  - 8.1

before_install: phpenv config-add ./tests/php.ini

install:
  - composer install --no-interaction --no-progress --no-suggest --optimize-autoloader

script:
  - ./vendor/bin/phpunit -c phpunit.xml