language: php
dist: trusty
sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

before_install: phpenv config-add ./tests/php.ini

install:
  - composer install --no-interaction --no-progress --no-suggest --optimize-autoloader

script:
  - ./vendor/bin/phpunit -c phpunit.xml